name: Deploy Godot HTML5 to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to your branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Download Godot v4.2.2 headless binary
      - name: Download Godot
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux_headless.64.zip
          unzip Godot_v4.2.2-stable_linux_headless.64.zip -d godot
          chmod +x godot/Godot_v4.2.2-stable_linux_headless.64

      # Step 3: Export the project to HTML5
      - name: Export to HTML5
        run: |
          mkdir -p docs
          godot/Godot_v4.2.2-stable_linux_headless.64 --export "HTML5" ./docs/index.html

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
